### ISSUE TITLE
Problemas con el módulo concursos

### ISSUE THREAD

**Issue by cmonsalvec** [CodeArmy01/AppRadio-Admin#4]
Estimados, favor revisar el issue que había colocado antes, pues no quedé plenamente satisfecho en cuanto a su solución

**Comment by luibasantes** [comment]
Actualmente me encuentro probando el modulo de concursos y efectivamente esta fallando.
El problema procedera a ser atendido en el transcurso de la semana.
@CodeArmy01/development Atender.

**Comment by luibasantes** [comment]
Se agrega la prioridad alta debido a que es un problema sin resolver de un modulo con un nivel de uso frecuente en el sistema, lo cual afecta fuertemente al sistema.

**Comment by luibasantes** [comment]
Se procede a asignar al usuario @jjcrowHawk  del @CodeArmy01/development equipo de desarrollo .

**Comment by jjcrowHawk** [comment]
El problema tiene un impacto alto, ya que el módulo es una parte importante dentro del proyecto, y no está realizando las funcionalidades importantes del mismo.

**Comment by jjcrowHawk** [comment]
Se ha corregido el problema, @alixferrin por favor proceda a realizar las pruebas del sistema y de integración para verificar su correcto funcionamiento

**Comment by alixferrin** [comment]
Se realizaron las pruebas con los cambios realizados por parte de @jjcrowHawk. Se verificó el correcto funcionamiento del módulo concurso y su interacción con los otros módulos del admin, se compararon los resultados obtenidos con los resultados esperados y no se han encontrado fallas en las pruebas.

**Comment by alixferrin** [comment]
Por favor revisar si el problema ha sido resuelto correctamente @cmonsalvec

**Comment by alixferrin** [comment]
> Se realizaron las pruebas con los cambios realizados por parte de @jjcrowHawk. Se verificó el correcto funcionamiento del módulo concurso y su interacción con los otros módulos del admin, se compararon los resultados obtenidos con los resultados esperados y no se han encontrado fallas en las pruebas.

Por favor @JoeSvr95 revisar si todas las actividades están funcionando correctamente.

**Comment by JoeSvr95** [comment]
@cmonsalvec Se ha verificado las correcciones al modulo se han realizado con éxito.

Ahora que el módulo está en producción no se presentan errores y está trabajando con éxito.

**Comment by cmonsalvec** [comment]
Gracias, el problema ha sido resuelto. Por favor asegurarse de completar todos los pasos metodológicos acordados antes de cerrar el ticket. Notificarme si es cerrado.

**Comment by luibasantes** [comment]
Dado a que el problema ha sido resuelto y se obtuvo la confirmación del cliente , se procede a **cerrar el issue** y se va a monitorear el modulo en produccion. @cmonsalvec
